# ruff: noqa: PT009, PT027 -- standard-library unittest assertions
"""Source preparation and reader-guide contracts."""

import base64
import importlib.util
import json
import re
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BODY_EXAMPLES = {
    "errors",
    "maintenance",
    "missing",
    "gone",
    "acknowledgement",
    "waf-html",
    "waf-json",
    "js",
    "captcha",
    "policy",
    "ddos-js",
    "bot-block",
}
PAGE_PURPOSES = [
    ("index", "Custom Responses", "Choose"),
    ("maintenance", "Maintenance", "without forwarding"),
    ("missing-resources", "Missing and retired resources", "404"),
    ("acknowledgement", "Static acknowledgement", "processing"),
    ("error-responses", "Error responses", "generated by the edge"),
    ("redirects", "Redirects", "method"),
    ("headers-cookies", "Headers and cookies", "scope"),
    ("cors", "Cross-origin access (CORS)", "origin"),
    ("masking", "Data masking", "selected"),
    ("blocked-requests", "WAF blocking", "firewall"),
    ("rate-limits", "Rate limits", "identification"),
    ("browser-verification", "JavaScript challenge", "host"),
    ("captcha-verification", "CAPTCHA verification", "un-verified"),
    ("conditional-challenges", "Conditional challenges", "selected"),
    ("bot-configuration", "Bot Defense configuration", "configuration-only"),
    ("configuration-reference", "Configuration reference", "fragments"),
]


class DocumentationTests(unittest.TestCase):
    def setUp(self):
        spec = importlib.util.spec_from_file_location(
            "prepare_snippets", ROOT / "scripts/prepare_snippets.py"
        )
        assert spec is not None
        assert spec.loader is not None
        self.prepare = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(self.prepare)

    def test_output_is_deterministic_and_exact(self):
        with tempfile.TemporaryDirectory() as temp:
            output = Path(temp)
            self.prepare.prepare(ROOT, output)
            first = {p.name: p.read_bytes() for p in output.iterdir()}
            self.prepare.prepare(ROOT, output)
            self.assertEqual(first, {p.name: p.read_bytes() for p in output.iterdir()})
            for item in self.prepare.SELECTIONS:
                source = json.loads((ROOT / item["source"]).read_text())
                value = self.prepare.select(source, item["pointer"])
                actual = (output / item["output"]).read_text()
                if item.get("decode"):
                    self.assertEqual(
                        actual, base64.b64decode(value[10:], validate=True).decode()
                    )
                else:
                    self.assertEqual(
                        json.loads(actual),
                        self.prepare.resource_fragment(item, value, primary=True),
                    )
                    exact = output / item["output"].replace(".json", "-encoded.json")
                    self.assertEqual(
                        json.loads(exact.read_text()),
                        self.prepare.resource_fragment(item, value, primary=False),
                    )

    def test_source_change_updates_example(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            (root / "terraform").mkdir()
            (root / "examples").mkdir()
            for source in {i["source"] for i in self.prepare.SELECTIONS}:
                (root / source).write_bytes((ROOT / source).read_bytes())
            tf_path = root / "terraform/scenarios.tf.json"
            tf = json.loads(tf_path.read_text())
            tf["resource"]["xcsh_http_loadbalancer"]["actions"]["routes"][2][
                "redirect_route"
            ][0]["route_redirect"][0]["response_code"] = 307
            tf_path.write_text(json.dumps(tf))
            self.prepare.prepare(root, root / "out")
            self.assertIn(
                '"response_code": 307', (root / "out/redirect.json").read_text()
            )

    def test_fail_closed(self):
        with tempfile.TemporaryDirectory() as temp:
            output = Path(temp)
            bad = dict(self.prepare.SELECTIONS[0], pointer="/missing")
            collision = dict(self.prepare.SELECTIONS[0], output="errors-encoded.json")
            for selections in [
                [bad],
                [self.prepare.SELECTIONS[0]] * 2,
                [collision, self.prepare.SELECTIONS[0]],
                [self.prepare.SELECTIONS[0], collision],
            ]:
                with self.assertRaises(ValueError):
                    self.prepare.prepare(ROOT, output, selections)
                self.assertEqual(list(output.iterdir()), [])
        for value in [
            "string:///!",
            "string:///YQ",
            "string:/// /w==",
            "https://example.com",
            "string:////w==",
        ]:
            with self.assertRaises(ValueError):
                self.prepare.decode(value)
        with self.assertRaises(ValueError):
            self.prepare.select({"a": [1]}, "/a/01")
        self.assertEqual(self.prepare.select({"a/b": {"~x": 2}}, "/a~1b/~0x"), 2)

    def test_malformed_source_body_prevents_all_output(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            for source in {i["source"] for i in self.prepare.SELECTIONS}:
                (root / source).parent.mkdir(parents=True, exist_ok=True)
                (root / source).write_bytes((ROOT / source).read_bytes())
            tf_path = root / "terraform/scenarios.tf.json"
            tf = json.loads(tf_path.read_text())
            mapping = tf["resource"]["xcsh_http_loadbalancer"]["errors"]["more_option"][
                0
            ]["custom_errors"]
            mapping["3"] = "string:///!"
            tf_path.write_text(json.dumps(tf))
            with self.assertRaises(ValueError):
                self.prepare.prepare(root, root / "out")
            self.assertFalse((root / "out").exists())

    def test_projection_preserves_arrays_and_object_blocks(self):
        with tempfile.TemporaryDirectory() as temp:
            output = Path(temp)
            self.prepare.prepare(ROOT, output)
            route = json.loads((output / "maintenance.json").read_text())["spec"][
                "routes"
            ]
            self.assertIsInstance(route, list)
            self.assertIsInstance(route[0]["direct_response_route"], dict)
            self.assertEqual(
                route[0]["direct_response_route"]["route_direct_response"][
                    "response_body_encoded"
                ],
                "<ENCODED_RESPONSE_BODY>",
            )
            policy = json.loads((output / "policy.json").read_text())["spec"][
                "policy_based_challenge"
            ]
            self.assertIsInstance(policy, dict)
            self.assertIsInstance(policy["rule_list"]["rules"], list)
            self.assertIsInstance(policy["rule_list"]["rules"][0]["spec"], dict)
            fallback = json.loads((output / "maintenance-fallback.json").read_text())[
                "spec"
            ]["more_option"]
            self.assertEqual(set(fallback), {"custom_errors"})
            self.assertEqual(
                fallback["custom_errors"]["503"], "<ENCODED_RESPONSE_BODY>"
            )
            metadata = json.loads((output / "metadata.json").read_text())["spec"][
                "more_option"
            ]
            self.assertEqual(
                set(metadata),
                {
                    "response_headers_to_add",
                    "response_headers_to_remove",
                    "response_cookies_to_add",
                    "response_cookies_to_remove",
                },
            )
            ref = json.loads((output / "waf-attach.json").read_text())["spec"][
                "app_firewall"
            ]
            self.assertEqual(
                ref, {"name": "<APP_FIREWALL_NAME>", "namespace": "<XC_NAMESPACE>"}
            )

    def test_feature_projections_have_complete_narrow_relationships(self):
        with tempfile.TemporaryDirectory() as temp:
            output = Path(temp)
            self.prepare.prepare(ROOT, output)

            def spec(name):
                return json.loads((output / name).read_text())["spec"]

            self.assertEqual(
                set(spec("maintenance-fallback.json")["more_option"]["custom_errors"]),
                {"503"},
            )
            self.assertEqual(
                set(spec("direct-error-bodies.json")["more_option"]["custom_errors"]),
                {"404", "410"},
            )
            self.assertEqual(
                spec("rate-limiter-identity.json")["user_identification"],
                [{"name": "<USER_IDENTIFICATION_NAME>", "namespace": "<XC_NAMESPACE>"}],
            )
            routes = spec("errors-fault.json")["routes"]
            self.assertEqual(len(routes), 2)
            self.assertEqual(
                [route["simple_route"]["path"]["path"] for route in routes],
                ["/fault/503", "/fault/504"],
            )

    def test_https_redirect_projection_tracks_source_and_rejects_wrong_type(self):
        item = next(
            item
            for item in self.prepare.SELECTIONS
            if item["output"] == "https-redirect.json"
        )
        source = json.loads((ROOT / item["source"]).read_text())
        value = self.prepare.select(source, item["pointer"])
        self.assertEqual(
            self.prepare.resource_fragment(item, value, primary=True),
            {"spec": {"https_auto_cert": {"http_redirect": True}}},
        )
        self.assertEqual(
            self.prepare.resource_fragment(
                item, [{"http_redirect": False}], primary=True
            ),
            {"spec": {"https_auto_cert": {"http_redirect": False}}},
        )
        with self.assertRaises(ValueError):
            self.prepare.resource_fragment(
                item, [{"http_redirect": "true"}], primary=True
            )

    def test_verified_additions_keep_their_measured_limits(self):
        proof = json.loads(
            (ROOT / "acceptance/additional-response-proof.json").read_text()
        )
        self.assertFalse(proof["infrastructure_modified"])
        self.assertEqual(len(proof["verified_additions"]), 2)
        redirect, request_id = proof["verified_additions"]
        self.assertEqual(redirect["observations"]["GET_and_POST_status"], 301)
        self.assertTrue(
            request_id["observations"][
                "exact_accepted_template_with_request_id_substituted"
            ]
        )
        self.assertTrue(
            request_id["observations"]["distinct_IDs_across_repeat_requests"]
        )
        self.assertTrue(
            request_id["observations"]["healthy_control_contains_no_substituted_ID"]
        )
        redirects = (ROOT / "docs/en/redirects.mdx").read_text()
        errors = (ROOT / "docs/en/error-responses.mdx").read_text()
        self.assertIn("file=../_data/https-redirect.json", redirects)
        self.assertIn("301", redirects)
        self.assertIn("does not guarantee POST", redirects)
        self.assertIn("repeat", errors.lower())
        self.assertIn("does not prove", errors)
        for digest in proof["protected_evidence_sha256"].values():
            self.assertRegex(digest, r"^[a-f0-9]{64}$")

    def test_projection_rejects_unknown_types_and_cardinality(self):
        schema = self.prepare.CONTRACT["resources"]["http_loadbalancer"]
        for value in [
            {"unknown": {}},
            {"js_challenge": []},
            {"js_challenge": [{}, {}]},
            {"js_challenge": [{"cookie_expiry": True}]},
            {"js_challenge": [{"cookie_expiry": "300"}]},
            {"routes": {}},
            {"js_challenge": [{"unknown": 1}]},
            {"js_challenge": [{"custom_page": "https://example.com"}]},
            {"more_option": [{"custom_errors": {"299": "string:///YQ=="}}]},
        ]:
            with self.subTest(value=value), self.assertRaises(ValueError):
                self.prepare.project(value, schema)

    def test_multiple_genuine_array_items_survive(self):
        schema = self.prepare.CONTRACT["resources"]["http_loadbalancer"]
        route = {
            "redirect_route": [
                {"path": [{"path": "/old"}], "route_redirect": [{"response_code": 302}]}
            ]
        }
        result = self.prepare.project({"routes": [route, route]}, schema)
        self.assertEqual(len(result["routes"]), 2)
        self.assertIsInstance(result["routes"][0]["redirect_route"]["path"], dict)

    def test_example_mutation_does_not_change_sources(self):
        before = {
            source: (ROOT / source).read_bytes()
            for source in {i["source"] for i in self.prepare.SELECTIONS}
        }
        with tempfile.TemporaryDirectory() as temp:
            self.prepare.prepare(ROOT, Path(temp))
        self.assertEqual(
            before, {source: (ROOT / source).read_bytes() for source in before}
        )

    def test_contract_has_pinned_sources_and_bounded_resources(self):
        contract = self.prepare.CONTRACT
        self.assertEqual(
            set(contract["resources"]),
            {
                "http_loadbalancer",
                "app_firewall",
                "rate_limiter",
                "user_identification",
            },
        )
        for source in contract["sources"]:
            self.assertRegex(source["sha256"], r"^[a-f0-9]{64}$")
            self.assertTrue(source["url"].startswith("https://docs.cloud.f5.com/"))
        for schema in contract["definitions"].values():
            self.assertIn("type", schema)

    def test_selector_ledger_tracks_current_sources(self):
        ledger = (ROOT / "operator/snippet-provenance.md").read_text()
        for item in self.prepare.SELECTIONS:
            row = f"| `{item['output']}` | `{item['source']}` | `{item['pointer']}` |"
            self.assertIn(row, ledger)
        self.assertEqual(
            ledger.count(" | `terraform/scenarios.tf.json` | ")
            + ledger.count(" | `examples/bot-defense.json` | "),
            len(self.prepare.SELECTIONS),
        )

    def test_all_scenarios_have_one_disposition(self):
        coverage = json.loads((ROOT / "operator/scenario-coverage.json").read_text())
        inventory = json.loads((ROOT / "scenarios.json").read_text())
        self.assertEqual(set(coverage), {i["id"] for i in inventory})
        for item in inventory:
            page = coverage[item["id"]]
            if item["group"] in {"control", "index"}:
                self.assertEqual(page, "supporting-fixture")
            else:
                self.assertTrue((ROOT / "docs/en" / (page + ".mdx")).is_file())
            if item["group"] == "bot":
                self.assertEqual(page, "bot-configuration")
                self.assertEqual(item["verification"], "configuration-only")

    def test_only_verified_live_paths_are_linked(self):
        record = json.loads((ROOT / "acceptance/current-iteration.json").read_text())
        inventory = json.loads((ROOT / "scenarios.json").read_text())
        verified = set(record["verified_live_scenarios"])
        published = set(record["published_live_scenarios"])
        self.assertTrue(published <= verified)
        expected = {
            f"https://{item['hostname']}{item['trigger']}"
            for item in inventory
            if item["id"] in published
        }
        linked = set()
        for page in (ROOT / "docs/en").glob("*.mdx"):
            linked.update(
                re.findall(
                    r"\]\((https://[a-z0-9.-]+\.f5-sales-demo\.com/[^)\s]*)\)",
                    page.read_text(),
                )
            )
        self.assertEqual(linked, expected)

    def test_editorial_and_includes(self):
        pages = [(slug, title) for slug, title, _ in PAGE_PURPOSES]
        outputs = {item["output"] for item in self.prepare.SELECTIONS}
        valid_includes = outputs | {
            name.replace(".json", "-encoded.json")
            for name in outputs
            if name.endswith(".json")
        }
        used_includes = set()
        for order, (slug, title) in enumerate(pages, start=1):
            text = (ROOT / "docs/en" / (slug + ".mdx")).read_text()
            self.assertIn(f"title: {title}\n", text, slug)
            self.assertRegex(text, r"(?m)^description: .+", slug)
            self.assertIn(f"  order: {order}\n", text, slug)
            self.assertIn(
                PAGE_PURPOSES[order - 1][2].lower(),
                text.split("---", 2)[2].split("\n## ")[0].lower(),
                slug,
            )
            headings = re.findall(r"(?m)^## (.+)$", text)
            self.assertEqual(len(headings), len(set(headings)), slug)
            self.assertEqual("tableOfContents: false\n" in text, not headings, slug)
            self.assertNotIn("<ENCODED_RESPONSE_BODY>", text, slug)
            self.assertNotIn("../demo-panel/", text, slug)
            self.assertNotIn("assets/demo-panel.html", text, slug)
            includes = re.findall(r"file=\.\./_data/([^\s]+)", text)
            for filename in includes:
                self.assertIn(filename, valid_includes, slug)
            used_includes.update(includes)
            if slug not in {"index", "configuration-reference"}:
                self.assertIn("Visitor", text, slug)
                self.assertRegex(
                    text,
                    r"\*\*Expected (?:result|configuration)(?: \(un-verified\))?:\*\*",
                )
                self.assertTrue(any(name.endswith(".json") for name in includes))
            self.assertNotRegex(
                text,
                r"\.\./(?:deployment|verification|branding|teardown|ownership|scenarios)/",
            )
        self.assertEqual(
            {path.stem for path in (ROOT / "docs/en").glob("*.mdx")},
            {slug for slug, _ in pages},
        )
        expected_includes = {
            name for name in outputs if name.removesuffix(".json") not in BODY_EXAMPLES
        } | {name + "-encoded.json" for name in BODY_EXAMPLES}
        self.assertEqual(used_includes, expected_includes)
        self.assertEqual(
            {name for name in used_includes if name.endswith("-encoded.json")},
            {name + "-encoded.json" for name in BODY_EXAMPLES},
        )
        for slug in {slug for slug, _ in pages} - {
            "index",
            "configuration-reference",
        }:
            text = (ROOT / "docs/en" / (slug + ".mdx")).read_text()
            for name in BODY_EXAMPLES:
                encoded = f"file=../_data/{name}-encoded.json"
                if encoded not in text:
                    continue
                self.assertEqual(text.count(encoded), 1, slug)
                self.assertNotIn(f"file=../_data/{name}.json", text, slug)
                preview = f"file=../_data/{name}.html"
                if preview in text:
                    self.assertLess(text.index(encoded), text.index(preview), slug)
                    self.assertIn("decoded preview", text.lower(), slug)

        landing = (ROOT / "docs/en/index.mdx").read_text()
        cards = re.findall(
            r'<LinkCard title="([^"]+)" description="([^"]+)" '
            r'href="\./([^/]+)/" />',
            landing,
        )
        self.assertEqual(
            [(slug, title) for title, _, slug in cards],
            [
                (slug, title)
                for slug, title in pages
                if slug not in {"index", "configuration-reference"}
            ],
        )
        self.assertEqual(
            re.findall(r"(?m)^## (.+)$", landing),
            [
                "Application responses",
                "Routing and response data",
                "Security checks and blocks",
            ],
        )
        self.assertEqual(
            landing.count("[Configuration reference](./configuration-reference/)"), 1
        )
        blocking = (ROOT / "docs/en/blocked-requests.mdx").read_text()
        self.assertLess(
            blocking.index("file=../_data/waf-json-encoded.json"),
            blocking.index("file=../_data/waf-json-body.json"),
        )
        for _, description, _ in cards:
            self.assertTrue(description.endswith("."), description)


if __name__ == "__main__":
    unittest.main()
